# Generated by Django 4.2.11 on 2025-05-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_partydistribution_representative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partydistribution',
            old_name='year',
            new_name='daesu',
        ),
        migrations.AddField(
            model_name='partydistribution',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
