# Generated by Django 4.2.11 on 2025-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_year_partydistribution_daesu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='EV_INST_NM',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='EV_PLC',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
