# Generated by Django 4.2.11 on 2025-06-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_bill_daesu_alter_partydistribution_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representative',
            old_name='year',
            new_name='daesu',
        ),
        migrations.AlterField(
            model_name='partydistribution',
            name='percentage',
            field=models.FloatField(default='0', null=True),
        ),
    ]
