# Generated by Django 5.2 on 2025-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=50, unique=True)),
                ('bill_name', models.CharField(max_length=200)),
                ('proposer', models.CharField(blank=True, max_length=100, null=True)),
                ('propose_dt', models.CharField(blank=True, max_length=20, null=True)),
                ('committee', models.CharField(blank=True, max_length=100, null=True)),
                ('proc_result', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
