# Generated by Django 5.2 on 2025-05-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='bill_id',
            new_name='bill_no',
        ),
        migrations.AddField(
            model_name='bill',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_kind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
