# Generated by Django 5.2 on 2025-04-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCH_KIND', models.CharField(max_length=20)),
                ('SCH_CN', models.TextField()),
                ('SCH_DT', models.CharField(max_length=100)),
                ('SCH_TM', models.CharField(default='0000-00-00', max_length=50, null=True)),
                ('CONF_DIV', models.CharField(default='0', max_length=50, null=True)),
                ('CMIT_NM', models.CharField(default='0', max_length=50, null=True)),
                ('CONF_SESS', models.CharField(default='0', max_length=50, null=True)),
                ('CONF_DGR', models.CharField(default='0', max_length=50, null=True)),
                ('EV_INST_NM', models.CharField(default='0', max_length=50, null=True)),
                ('EV_PLC', models.CharField(default='0', max_length=50, null=True)),
            ],
        ),
    ]
