# Generated by Django 4.2.11 on 2025-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bill_ev_inst_nm_alter_bill_ev_plc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='daesu',
            field=models.IntegerField(default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='EV_INST_NM',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='EV_PLC',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
    ]
