# Generated by Django 4.2.11 on 2025-05-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bill_daesu_alter_bill_ev_inst_nm_alter_bill_ev_plc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='daesu',
        ),
        migrations.AlterField(
            model_name='partydistribution',
            name='percentage',
            field=models.FloatField(null=True),
        ),
    ]
