# Generated by Django 5.2 on 2025-05-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendas', '0002_rename_bill_id_bill_bill_no_bill_age_bill_bill_kind'),
        ('members', '0003_remove_assemblymember_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_result', models.CharField(max_length=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='agendas.bill')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='members.assemblymember')),
            ],
        ),
    ]
