# Generated by Django 5.2 on 2025-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_rename_bill_id_bill_bill_no_bill_age_bill_bill_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
