# Generated by Django 5.2 on 2025-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_alter_bill_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
