# Generated by Django 5.2 on 2025-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_alter_bill_bill_id_alter_bill_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='propose_dt',
        ),
        migrations.AddField(
            model_name='bill',
            name='rgs_proc_dt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
