# Generated by Django 5.2 on 2025-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mona_cd', models.CharField(max_length=20, unique=True)),
                ('party', models.CharField(max_length=100, null=True)),
                ('committee', models.CharField(max_length=100, null=True)),
                ('elect_gbn', models.CharField(max_length=20, null=True)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('homepage', models.URLField(null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('title', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
