# Generated by Django 5.2 on 2025-05-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblymember',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
