# Generated by Django 5.2 on 2025-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_assemblymember_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblymember',
            name='image_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assemblymember',
            name='mona_cd',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
