# Generated by Django 5.2 on 2025-05-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_assemblymember_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblymember',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
