# Generated by Django 5.2 on 2025-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_assemblymember_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblymember',
            name='assem_addr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assemblymember',
            name='hj_nm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assemblymember',
            name='secretary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assemblymember',
            name='staff',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assemblymember',
            name='image_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
