# Generated by Django 5.2 on 2025-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_assemblymember_assem_addr_assemblymember_hj_nm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblymember',
            name='unit_cd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
