# Generated by Django 5.2 on 2025-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_assemblymember_unit_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblymember',
            name='unit_cd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
